const WalletActionTypes = {
  RESET_WALLET: 'RESET_WALLET',
  SET_ADDRESS_START: 'SET_ADDRESS_START',
  SET_ADDRESS_SUCCESS: 'SET_ADDRESS_SUCCESS',
  SET_ADDRESS_FAILURE: 'SET_ADDRESS_FAILURE',
  GET_TOTAL_GAS_USED_START: 'GET_TOTAL_GAS_USED_START',
  GET_TOTAL_GAS_USED_SUCCESS: 'GET_TOTAL_GAS_USED_SUCCESS',
  GET_TOTAL_GAS_USED_FAILURE: 'GET_TOTAL_GAS_USED_FAILURE',
  GET_NFTS_START: 'GET_NFTS_START',
  GET_NFTS_SUCCESS: 'GET_NFTS_SUCCESS',
  GET_NFTS_FAILURE: 'GET_NFTS_FAILURE',
};

export default WalletActionTypes;
